
import java.awt.BorderLayout;
import java.io.File;
import java.util.List;
import java.util.ArrayList;
import javafx.stage.FileChooser;
import javax.swing.JPanel;
import org.jfree.chart.ChartPanel;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.jfree.chart.JFreeChart;
import java.lang.Boolean;
import org.jfree.ui.RefineryUtilities;
import org.jfree.chart.event.ChartChangeEvent;
import java.awt.*;
import javax.swing.BoxLayout;
import java.awt.event.*;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package weather.station;

/**
 *
 * @author 7053313
 */
public class MainWindow extends JFrame implements ItemListener, ActionListener
{

    /**
     * Creates new form MainWindow
     */
    public MainWindow()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
		TimeFrame = new ButtonGroup();
        FileChooser = new javax.swing.JFileChooser();
        MeanTemperature = new javax.swing.JCheckBox("Mean Temperature");
        HighLowTemperature = new javax.swing.JCheckBox("High/Low Temperature");
        MeanWindSpeed = new javax.swing.JCheckBox("Mean Wind Speed");
        MaximumWindSpeed = new javax.swing.JCheckBox("Maximum Wind Speed");
        PrevailingWindDirection = new javax.swing.JCheckBox("Prevailing Wind Direction");
        Rainfall = new javax.swing.JCheckBox("Rainfall");
        Daily = new javax.swing.JRadioButton("Daily");
        Weekly = new javax.swing.JRadioButton("Weekly");
        Monthly = new javax.swing.JRadioButton("Monthly");
        Yearly = new javax.swing.JRadioButton("Yearly");
        weatherGraph = new WeatherGraph( new ArrayList<WeatherPoint>() );       
        GraphPanel = new ChartPanel( weatherGraph.getGraph() );        
        MenuBar = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        Open = new javax.swing.JMenuItem();
        Seperator = new javax.swing.JPopupMenu.Separator();
        Exit = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        XMLLoaded = false;
        XMLFileName = "";
		Panel = new javax.swing.JPanel();
		TimePanel = new javax.swing.JPanel();
		GraphOptionPanel = new javax.swing.JPanel();
        weatherPoints = new ArrayList<WeatherPoint>();

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        MeanTemperature.setMnemonic(KeyEvent.VK_C);
		MeanTemperature.setSelected(false);

		HighLowTemperature.setMnemonic(KeyEvent.VK_C);
		HighLowTemperature.setSelected(false);

		MeanWindSpeed.setMnemonic(KeyEvent.VK_C);
		MeanWindSpeed.setSelected(false);

		MaximumWindSpeed.setMnemonic(KeyEvent.VK_C);
		MaximumWindSpeed.setSelected(false);

		PrevailingWindDirection.setMnemonic(KeyEvent.VK_C);
		PrevailingWindDirection.setSelected(false);

		Rainfall.setMnemonic(KeyEvent.VK_C);
		Rainfall.setSelected(false);

		MeanTemperature.addItemListener(this);
		HighLowTemperature.addItemListener(this);
		MeanWindSpeed.addItemListener(this);
		MaximumWindSpeed.addItemListener(this);
		PrevailingWindDirection.addItemListener(this);
		Rainfall.addItemListener(this);

		Daily.setMnemonic(KeyEvent.VK_C);
		Daily.setActionCommand("Daily");
		Daily.setSelected(true);
		

		Weekly.setMnemonic(KeyEvent.VK_C);
		Weekly.setActionCommand("Weekly");
	
		Monthly.setMnemonic(KeyEvent.VK_C);
		Monthly.setActionCommand("Monthly");

		Yearly.setMnemonic(KeyEvent.VK_C);
		Yearly.setActionCommand("Yearly");

		TimeFrame.add(Daily);
		TimeFrame.add(Weekly);
		TimeFrame.add(Monthly);
		TimeFrame.add(Yearly);

		Daily.addActionListener(this);
		Weekly.addActionListener(this);
		Monthly.addActionListener(this);
		Yearly.addActionListener(this);

        File.setText("File");

        Open.setText("Open");
        Open.addActionListener(new java.awt.event.ActionListener() 
        {
            public void actionPerformed(java.awt.event.ActionEvent evt) 
            {
                OpenActionPerformed(evt);
            }
        });
        File.add(Open);
        File.add(Seperator);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() 
        {
            public void actionPerformed(java.awt.event.ActionEvent evt) 
            {
                ExitActionPerformed(evt);
            }
        });
        File.add(Exit);

        MenuBar.add(File);

        Edit.setText("Edit");
        MenuBar.add(Edit);
        setJMenuBar(MenuBar);

		Panel.setLayout(new BorderLayout());
		TimePanel.setLayout(new BoxLayout(TimePanel, BoxLayout.Y_AXIS));
		GraphOptionPanel.setLayout(new BoxLayout(GraphOptionPanel, BoxLayout.Y_AXIS));

		TimePanel.add(Daily);
		TimePanel.add(Weekly);
		TimePanel.add(Monthly);
		TimePanel.add(Yearly);
		GraphOptionPanel.add(MeanTemperature);
		GraphOptionPanel.add(HighLowTemperature);
		GraphOptionPanel.add(MeanWindSpeed);
		GraphOptionPanel.add(MaximumWindSpeed);
		GraphOptionPanel.add(PrevailingWindDirection);
		GraphOptionPanel.add(Rainfall);
		Panel.add(TimePanel, BorderLayout.WEST);
		Panel.add(GraphPanel, BorderLayout.CENTER);
		Panel.add(GraphOptionPanel, BorderLayout.EAST);

		setContentPane(Panel);
		this.setTitle("WWWWHHHHHYYYYY");
		this.pack();
		this.setVisible(true);
   
    }// </editor-fold>//GEN-END:initComponents

	public void itemStateChanged(ItemEvent e)
	{
		Object source = e.getItemSelectable();

		if(source == MeanTemperature)
		{
			System.out.println("Mean Temperature chosen.");
		    if(e.getStateChange() == ItemEvent.SELECTED )
		    {
		        System.out.println( "is selected" );
		        //weatherGraph.showLine( 0 );
		    }
		    else
		    {
		        System.out.println( "It aint no selected" );
		        //weatherGraph.hideLine( 0 );
		    }        
		    //update( GraphPanel, weatherGraph.getGraph() );
		}

		else if(source == HighLowTemperature)
		{
			System.out.println("High/Low Temperature chosen.");
		    if(e.getStateChange() == ItemEvent.SELECTED )
		    {
		        System.out.println( "is selected" );
		        weatherGraph.showLine( 0 );
		    }
		    else
		    {
		        System.out.println( "It aint no selected" );
		        weatherGraph.hideLine( 0 );
		    }        
		    update( GraphPanel, weatherGraph.getGraph() );
		}

		else if(source == MeanWindSpeed)
		{
			System.out.println("Mean Wind Speed chosen.");
		    if(e.getStateChange() == ItemEvent.SELECTED )
		    {
		        System.out.println( "is selected" );
		        //weatherGraph.showLine( 0 );
		    }
		    else
		    {
		        System.out.println( "It aint no selected" );
		        //weatherGraph.hideLine( 0 );
		    }        
		    //update( GraphPanel, weatherGraph.getGraph() );
		}

		else if(source == MaximumWindSpeed)
		{
			if( MaximumWindSpeed.isSelected() )
		    {
		        System.out.println( "Maximum Wind Speed is selected" );
		        weatherGraph.showLine( 3 );
		    }
		    else
		    {
		        System.out.println( "MWS: It aint no selected" );
		        weatherGraph.hideLine( 3 );
		    }
		    weatherGraph.showLine( 0 );
		    System.out.println("Mean Wind Speed chosen.");
		    update( GraphPanel, weatherGraph.getGraph() );
		}

		else if(source == PrevailingWindDirection)
		{
			System.out.println("Prevailing Wind Direction chosen.");
		    if(e.getStateChange() == ItemEvent.SELECTED )
		    {
		        System.out.println( "is selected" );
		        //weatherGraph.showLine( 0 );
		    }
		    else
		    {
		        System.out.println( "It aint no selected" );
		        //weatherGraph.hideLine( 0 );
		    }        
		    //update( GraphPanel, weatherGraph.getGraph() );
		}

		else if(source == Rainfall)
		{
			System.out.println("Rainfall chosen.");
		    if( Rainfall.isSelected() )
		    {
		        System.out.println( "is selected" );
		        weatherGraph.showLine( 9 );
		    }
		    else
		    {
		        System.out.println( "It aint no selected" );
		        weatherGraph.hideLine( 9 );
		    }
		    update( GraphPanel, weatherGraph.getGraph() );
		}
	}

	public void actionPerformed(ActionEvent e)
	{
		Object source = e.getActionCommand();

		if(source == "Daily")
		{
			System.out.println("Daily chosen.");
		}
		
		else if(source == "Weekly")
		{
			System.out.println("Weekly chosen.");
		}
	
		else if(source == "Monthly")
		{
			System.out.println("Monthly chosen.");
		}
	
		else if(source == "Yearly")
		{
			System.out.println("Yearly chosen.");
		}
	}

    private void ExitActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_ExitActionPerformed
        
        System.exit(0);
    
    }//GEN-LAST:event_ExitActionPerformed

    private void OpenActionPerformed(java.awt.event.ActionEvent evt)
    {//GEN-FIRST:event_OpenActionPerformed
        
        System.out.println("Open chosen.");
        
        // filter to only xml files
        FileNameExtensionFilter xmlFilter = new FileNameExtensionFilter( null, "xml" );
        FileChooser.setFileFilter( xmlFilter );
        
        // show the dialog box to select a file from
        int returnVal = FileChooser.showOpenDialog( null );
        
        // if file selection was a success
        if( returnVal == JFileChooser.APPROVE_OPTION )
        {
            System.out.println( "You chose to open this file: " + FileChooser.getSelectedFile().getName() );
        	XMLLoaded = true;
        	XMLFileName = FileChooser.getSelectedFile().getName();
        }
		
		GraphPanel.removeAll();
        weatherPoints = ParseXML.parseWeather( XMLFileName );
		weatherGraph = new WeatherGraph( weatherPoints );
		update(GraphPanel, weatherGraph.getGraph());

    	System.out.println( "Exiting Open Event Handler" );
        
    }//GEN-LAST:event_OpenActionPerformed

    public void update(ChartPanel GraphPanel, JFreeChart weatherGraph)
    {
		Panel.removeAll();
		GraphPanel = new ChartPanel(weatherGraph);
		GraphPanel.repaint();

		Panel.setLayout(new BorderLayout());
		TimePanel.setLayout(new BoxLayout(TimePanel, BoxLayout.Y_AXIS));
		GraphOptionPanel.setLayout(new BoxLayout(GraphOptionPanel, BoxLayout.Y_AXIS));

		TimePanel.add(Daily);
		TimePanel.add(Weekly);
		TimePanel.add(Monthly);
		TimePanel.add(Yearly);
		GraphOptionPanel.add(MeanTemperature);
		GraphOptionPanel.add(HighLowTemperature);
		GraphOptionPanel.add(MeanWindSpeed);
		GraphOptionPanel.add(MaximumWindSpeed);
		GraphOptionPanel.add(PrevailingWindDirection);
		GraphOptionPanel.add(Rainfall);
		Panel.add(TimePanel, BorderLayout.WEST);
		Panel.add(GraphPanel, BorderLayout.CENTER);
		Panel.add(GraphOptionPanel, BorderLayout.EAST);

		setContentPane(Panel);
		this.setTitle("WWWWHHHHHYYYYY");
		this.pack();
		this.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        try 
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } 
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 
        catch (InstantiationException ex) 
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run() 
            {
                MainWindow mainWindow = new MainWindow();
				mainWindow.setTitle("Weather Station");
				mainWindow.pack();
				RefineryUtilities.centerFrameOnScreen(mainWindow);
				mainWindow.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Daily;
    private javax.swing.JMenu Edit;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu File;
    private javax.swing.JFileChooser FileChooser;
    //private javax.swing.ButtonGroup GraphVariables;
    private javax.swing.JCheckBox HighLowTemperature;
    private javax.swing.JCheckBox MaximumWindSpeed;
    private javax.swing.JCheckBox MeanTemperature;
    private javax.swing.JCheckBox MeanWindSpeed;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JRadioButton Monthly;
    private javax.swing.JMenuItem Open;
    private javax.swing.JCheckBox PrevailingWindDirection;
    private javax.swing.JCheckBox Rainfall;
    private javax.swing.JPopupMenu.Separator Seperator;
    private javax.swing.ButtonGroup TimeFrame;
    private javax.swing.JRadioButton Weekly;
    private javax.swing.JRadioButton Yearly;
    private javax.swing.JPanel Panel;
    private javax.swing.JPanel TimePanel;
    private javax.swing.JPanel GraphOptionPanel;
    private WeatherGraph weatherGraph;
    private JFreeChart Graph;
    private ChartPanel GraphPanel;
    private java.lang.Boolean XMLLoaded;
    private String XMLFileName;
    private List<WeatherPoint> weatherPoints;
    // add the panel to the window and add the graph to the panel

    //private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
